### ISSUE TITLE
Compatibility with LocalStorage and IE (11 Tested)

### ISSUE THREAD

**Issue by vrgmatteo** [arnellebalane/hermes#1]
Hi, your API is really great! 
I used it and i find a couple issues when i used it on Internet Explorer(11) or in general in LocalStorage mode. I fix that and i'll suggest to you to apply correction.

For the general issue for LocalStorage i notice you make a control in receiving like this (null === e.oldValue). The problem is that "e.oldValue" is never "null" but is defined as empty string (""). So i change the control in  ("" === e.oldValue) and it worked.

Specifically for IE(11) you use (e.key.startsWidth(a)) but startsWidth method for Strings is not compatible with IE(11) (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith#Browser_compatibility).

I fix this issue adding the polyFill (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith#Polyfill) to the library.

I hope I was helpful

Long life and prosperity

**Comment by arnellebalane** [comment]
Hi @vrgmatteo! Thank you for your feedback and suggestions, I'll definitely get this fixed! 👍

**Comment by arnellebalane** [comment]
Hi @vrgmatteo , it looks like according to the Web Storage spec, `e.oldValue` may be `null` when the key is newly-added ([reference](https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-event)), which is what I'm checking for in the code.

Also, I am not using `e.key.startsWith` anywhere in the codebase.

You can keep using your workaround and changes to the library that works for your compatibility needs for IE11, but I won't be updating hermes with those for the meantime.

Have a pleasant day! 😃
