### ISSUE TITLE
Add to npmjs

### ISSUE THREAD

**Issue by Enchiridion** [arnellebalane/hermes#12]
Hi,
Could you add this to npmjs? I searched but couldn't find the "official" version of it, and the `hermes` name is already taken by another package.

**Comment by fardad-dev** [comment]
Hi, i have a fork of this package on NPM with `hermes-channel` name. If you like this I am glad to give you that.

**Comment by Joohansson** [comment]
> Hi, i have a fork of this package on NPM with `hermes-channel` name. If you like this I am glad to give you that.

This is very useful! Thanks a lot. But you have the wrong install instructions: npm i hermes --save
Should be npm i hermes-channel --save
