### ISSUE TITLE
Sending data between pages with different URLs

### ISSUE THREAD

**Issue by jarble** [arnellebalane/hermes#14]
Does Hermes include a method to send messages between pages with different URLs?
[This demo](https://hermes.arnelle.me/) works with only one URL, but it would be even better if there were a way to communicate between pages with several different URLs.

**Comment by quantrung9** [comment]
@jarble You can try https://github.com/jcubic/sysend.js to send messages cross-origin between tabs.

**Comment by arnellebalane** [comment]
@jarble Hi, no it doesn't, as it was built specifically only for same-origin URLs. 

The [`sysend.js`](https://github.com/jcubic/sysend.js) library that @quanengineering linked (thank you!) looks great, as it provides a similar API and seems to work across cross-origin tabs. Please try if that fits what you need, good luck! :+1:
