### ISSUE TITLE
Hermes doesn't work with IE 11 & Edge

### ISSUE THREAD

**Issue by elio-centrique** [arnellebalane/hermes#3]
Hi!
I'm a user of your API for a professionnal use and I just notice that it doesn't work anymore on IE 11 version 11.165.17134.0 and Edge version 42.17134.1.0.
I tried your demo and it's the same issue.
It still works on Firefox.
Cordially

**Comment by norfanos** [comment]
I can confirm this is the case as well. I came across your blog and this project in search for a solution. I may still go with it, and try to resolve the issue if possible. I'll share if I do.
